[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:api]
command=node /srv/api/dist/src/main.js
directory=/srv/api
user=pipebomb
autostart=true
autorestart=true
environment=BASE_PATH="/api",NODE_ENV="production"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20

[program:frontend]
command=node /srv/frontend/server.js
directory=/srv/frontend
user=pipebomb
autostart=true
autorestart=true
environment=NODE_ENV="production",PORT="3001",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=30
